# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5cb1c4d3d09de63617539a3f2d09433dc61f08350df80299e71cd31e19ccddd585ce63c4e0826daed95b97e68e2fec25abd51af3ed4c60c0619e0b730fe2762b

test:
  secret_key_base: c042ca671b543354881533c99cb1320e51ef9162ebd28b3a587e90c9a99fb596db7a2eab401b34e3e8dc1f05c63433c8b2dc370d50c3abc7b6561a209af29b77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
